[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm install --include=dev && npx tsc && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300

[env]
NODE_ENV = "production"
